<option value="FR">	FRANCE </option>
<option value="AD">	ANDORRE </option>
<option value="AE">	ÉMIRATS ARABES UNIS </option>
<option value="AF">	AFGHANISTAN </option>
<option value="AG">	ANTIGUA ET BARBUDA </option>
<option value="AL">	ALBANIE </option>
<option value="AM">	ARMENIE </option>
<option value="AO">	ANGOLA </option>
<option value="AR">	ARGENTINE </option>
<option value="AT">	AUTRICHE </option>
<option value="AU">	AUSTRALIE </option>
<option value="AZ">	AZERBAIDJAN </option>
<option value="BA">	BOSNIE-HERZEGOVINE </option>
<option value="BB">	BARBADE </option>
<option value="BD">	BANGLADESH </option>
<option value="BE">	BELGIQUE </option>
<option value="BF">	BURKINA FASO </option>
<option value="BG">	BULGARIE </option>
<option value="BH">	BAHREIN </option>
<option value="BI">	BURUNDI </option>
<option value="BJ">	BENIN </option>
<option value="BN">	BRUNEI DARUSSALAM </option>
<option value="BO">	BOLIVIE </option>
<option value="BQ">	BONAIRE, SAINT-EUSTACHE ET SABA </option>
<option value="BR">	BRESIL </option>
<option value="BS">	BAHAMAS </option>
<option value="BT">	BHOUTAN </option>
<option value="BW">	BOTSWANA </option>
<option value="BY">	BELARUS </option>
<option value="BZ">	BELIZE </option>
<option value="CA">	CANADA </option>
<option value="CD">	CONGO, LA REPUBLIQUE DEMOCRATIQUE </option>
<option value="CF">	CENTRAFRICAINE, REPUBLIQUE </option>
<option value="CG">	CONGO </option>
<option value="CH">	SUISSE </option>
<option value="CI">	COTE D'IVOIRE </option>
<option value="CL">	CHILI </option>
<option value="CM">	CAMEROUN </option>
<option value="CN">	CHINE </option>
<option value="CO">	COLOMBIE </option>
<option value="CR">	COSTA RICA </option>
<option value="CU">	CUBA </option>
<option value="CV">	CAP-VERT </option>
<option value="CW">	CURACAO </option>
<option value="CY">	CHYPRE </option>
<option value="CZ">	TCHEQUE, REPUBLIQUE </option>
<option value="DE">	ALLEMAGNE </option>
<option value="DJ">	DJIBOUTI </option>
<option value="DK">	DANEMARK </option>
<option value="DM">	DOMINIQUE </option>
<option value="DO">	DOMINICAINE, REPUBLIQUE </option>
<option value="DZ">	ALGERIE </option>
<option value="EC">	EQUATEUR </option>
<option value="EE">	ESTONIE </option>
<option value="EG">	EGYPTE </option>
<option value="ER">	ERYTHREE </option>
<option value="ES">	ESPAGNE </option>
<option value="ET">	ETHIOPIE </option>
<option value="FI">	FINLANDE </option>
<option value="FJ">	FIDJI </option>
<option value="FM">	MICRONESIE, ETATS FEDERES DE </option>
<option value="GA">	GABON </option>
<option value="GB">	ROYAUME-UNI </option>
<option value="GD">	GRENADE </option>
<option value="GE">	GEORGIE </option>
<option value="GH">	GHANA </option>
<option value="GM">	GAMBIE </option>
<option value="GN">	GUINEE </option>
<option value="GQ">	GUINEE EQUATORIALE </option>
<option value="GR">	GRECE </option>
<option value="GT">	GUATEMALA </option>
<option value="GW">	GUINEE-BISSAU </option>
<option value="GY">	GUYANA </option>
<option value="HK">	HONG KONG </option>
<option value="HN">	HONDURAS </option>
<option value="HR">	CROATIE </option>
<option value="HT">	HAITI </option>
<option value="HU">	HONGRIE </option>
<option value="ID">	INDONESIE </option>
<option value="IE">	IRLANDE </option>
<option value="IL">	ISRAEL </option>
<option value="IN">	INDE </option>
<option value="IQ">	IRAQ </option>
<option value="IR">	IRAN </option>
<option value="IS">	ISLANDE </option>
<option value="IT">	ITALIE </option>
<option value="JM">	JAMAIQUE </option>
<option value="JO">	JORDANIE </option>
<option value="JP">	JAPON </option>
<option value="KE">	KENYA </option>
<option value="KG">	KIRGHIZISTAN </option>
<option value="KH">	CAMBODGE </option>
<option value="KI">	KIRIBATI </option>
<option value="KM">	COMORES </option>
<option value="KN">	SAINT-KITTS-ET-NEVIS </option>
<option value="KP">	COREE DU NORD </option>
<option value="KR">	COREE DU SUD </option>
<option value="KW">	KOWEIT </option>
<option value="KZ">	KAZAKHSTAN </option>
<option value="LA">	LAOS </option>
<option value="LB">	LIBAN </option>
<option value="LC">	SAINTE-LUCIE </option>
<option value="LI">	LIECHTENSTEIN </option>
<option value="LK">	SRI LANKA </option>
<option value="LR">	LIBERIA </option>
<option value="LS">	LESOTHO </option>
<option value="LT">	LITUANIE </option>
<option value="LU">	LUXEMBOURG </option>
<option value="LV">	LETTONIE </option>
<option value="LY">	LIBYENNE, JAMAHIRIYA ARABE </option>
<option value="MA">	MAROC </option>
<option value="MC">	MONACO </option>
<option value="MD">	MOLDOVA, REPUBLIQUE DE </option>
<option value="ME">	MONTENEGRO </option>
<option value="MG">	MADAGASCAR </option>
<option value="MH">	MARSHALL, ILES </option>
<option value="MK">	MACEDOINE,L'EX-REPUBLIQUE YOUGOSL </option>
<option value="ML">	MALI </option>
<option value="MM">	MYANMAR </option>
<option value="MN">	MONGOLIE </option>
<option value="MR">	MAURITANIE </option>
<option value="MT">	MALTE </option>
<option value="MU">	MAURICE </option>
<option value="MV">	MALDIVES </option>
<option value="MW">	MALAWI </option>
<option value="MX">	MEXIQUE </option>
<option value="MY">	MALAISIE </option>
<option value="MZ">	MOZAMBIQUE </option>
<option value="NA">	NAMIBIE </option>
<option value="NE">	NIGER </option>
<option value="NG">	NIGERIA </option>
<option value="NI">	NICARAGUA </option>
<option value="NL">	PAYS-BAS </option>
<option value="NO">	NORVEGE </option>
<option value="NP">	NEPAL </option>
<option value="NR">	NAURU </option>
<option value="NZ">	NOUVELLE-ZELANDE </option>
<option value="OM">	OMAN </option>
<option value="PA">	PANAMA </option>
<option value="PE">	PEROU </option>
<option value="PG">	PAPOUASIE-NOUVELLE-GUINEE </option>
<option value="PH">	PHILIPPINES </option>
<option value="PK">	PAKISTAN </option>
<option value="PL">	POLOGNE </option>
<option value="PS">	PALESTINIEN OCCUPE, TERRITOIRE </option>
<option value="PT">	PORTUGAL </option>
<option value="PW">	PALAOS </option>
<option value="PY">	PARAGUAY </option>
<option value="QA">	QATAR </option>
<option value="RO">	ROUMANIE </option>
<option value="RS">	SERBIE </option>
<option value="RU">	RUSSIE, FEDERATION DE </option>
<option value="RW">	RWANDA </option>
<option value="SA">	ARABIE SAOUDITE </option>
<option value="SB">	SALOMON, ILES </option>
<option value="SC">	SEYCHELLES </option>
<option value="SD">	SOUDAN </option>
<option value="SE">	SUEDE </option>
<option value="SG">	SINGAPOUR </option>
<option value="SI">	SLOVENIE </option>
<option value="SK">	SLOVAQUIE </option>
<option value="SL">	SIERRA LEONE </option>
<option value="SM">	SAINT-MARIN </option>
<option value="SN">	SENEGAL </option>
<option value="SO">	SOMALIE </option>
<option value="SR">	SURINAME </option>
<option value="SS">	SUD SOUDAN </option>
<option value="ST">	SAO TOME-ET-PRINCIPE </option>
<option value="SV">	EL SALVADOR </option>
<option value="SX">	SAINT-MARTIN (PARTIE NEERLANDAISE) </option>
<option value="SY">	SYRIENNE, REPUBLIQUE ARABE </option>
<option value="SZ">	SWAZILAND </option>
<option value="TD">	TCHAD </option>
<option value="TG">	TOGO </option>
<option value="TH">	THAILANDE </option>
<option value="TJ">	TADJIKISTAN </option>
<option value="TL">	TIMOR-LESTE </option>
<option value="TM">	TURKMENISTAN </option>
<option value="TN">	TUNISIE </option>
<option value="TO">	TONGA </option>
<option value="TR">	TURQUIE </option>
<option value="TT">	TRINITE-ET-TOBAGO </option>
<option value="TV">	TUVALU </option>
<option value="TW">	TAIWAN, PROVINCE DE CHINE </option>
<option value="TZ">	TANZANIE, REPUBLIQUE-UNIE DE </option>
<option value="UA">	UKRAINE </option>
<option value="UG">	OUGANDA </option>
<option value="US">	ETATS-UNIS </option>
<option value="UY">	URUGUAY </option>
<option value="UZ">	OUZBEKISTAN </option>
<option value="VA">	VATICAN </option>
<option value="VC">	SAINT-VINCENT-ET-LES GRENADINES </option>
<option value="VE">	VENEZUELA </option>
<option value="VN">	VIET NAM </option>
<option value="VU">	VANUATU </option>
<option value="WS">	SAMOA </option>
<option value="XK">	KOSOVO </option>
<option value="YE">	YEMEN </option>
<option value="ZA">	AFRIQUE DU SUD </option>
<option value="ZM">	ZAMBIE </option>
<option value="ZW">	ZIMBABWE </option>